// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.AppDbContext;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(SiteDbContext))]
    partial class SiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("WebApp.Models.MenteeProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MentorshipRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MentorshipRequestId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MenteeProfiles");
                });

            modelBuilder.Entity("WebApp.Models.MentorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MentorshipRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MentorshipRequestId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MentorProfiles");
                });

            modelBuilder.Entity("WebApp.Models.MentorshipRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenteeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorshipRequests");
                });

            modelBuilder.Entity("WebApp.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedbackRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FeedbackSubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MenteeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UsersId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApp.Models.MenteeProfile", b =>
                {
                    b.HasOne("WebApp.Models.MentorshipRequest", null)
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("MentorshipRequestId");

                    b.HasOne("WebApp.Models.Session", null)
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("SessionId");

                    b.HasOne("WebApp.Models.User", "User")
                        .WithOne("MenteeProfile")
                        .HasForeignKey("WebApp.Models.MenteeProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApp.Models.MentorProfile", b =>
                {
                    b.HasOne("WebApp.Models.MentorshipRequest", null)
                        .WithMany("MentorProfiles")
                        .HasForeignKey("MentorshipRequestId");

                    b.HasOne("WebApp.Models.Session", null)
                        .WithMany("MentorProfiles")
                        .HasForeignKey("SessionId");

                    b.HasOne("WebApp.Models.User", "Users")
                        .WithOne("MentorProfile")
                        .HasForeignKey("WebApp.Models.MentorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApp.Models.MentorshipRequest", b =>
                {
                    b.HasOne("WebApp.Models.User", "Mentee")
                        .WithMany()
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.User", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("WebApp.Models.Session", b =>
                {
                    b.HasOne("WebApp.Models.MentorshipRequest", "Request")
                        .WithMany("Sessions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("Request");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApp.Models.MentorshipRequest", b =>
                {
                    b.Navigation("MenteeProfiles");

                    b.Navigation("MentorProfiles");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("WebApp.Models.Session", b =>
                {
                    b.Navigation("MenteeProfiles");

                    b.Navigation("MentorProfiles");
                });

            modelBuilder.Entity("WebApp.Models.User", b =>
                {
                    b.Navigation("MenteeProfile");

                    b.Navigation("MentorProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
